// 툴의 모든 문구는 여기 모은다. 부처 표기: 군사 = 수호부, 반역 판정 · 선전 · 재교육 = 진리부. em dash 금지(lint:copy).

export const APP_NAME = '로드아웃 빌더'

/** 진리부 방송 문구. 한 줄 44자 이내(텔레타이프 3줄 고정 높이 기준). */
export const slogans = [
  '민주주의는 미리 준비한 자의 것입니다.',
  '배낭은 하나. 자유는 무한.',
  '출격 전 점검은 애국입니다.',
  '자유는 공짜가 아닙니다. 채권은 더더욱.',
  '진리부는 당신의 로드아웃을 이미 알고 있습니다.',
  '재보급은 권리가 아니라 특권입니다.',
  '팀킬 한 번은 실수. 두 번째부터는 통계.',
  '살아 돌아오는 것은 선택 사항. 임무 완수는 의무.',
  '당신의 전사는 기록됩니다. 기록은 4초간 보관됩니다.',
  '사령관은 당신을 믿습니다. 통계는 믿지 않습니다.',
  '평균 복무 시간 2분 40초. 신기록에 도전하십시오.',
  '지원무기를 두 개 들 수 있다는 소문은 반역 선전입니다.',
  '궤도 타격 요청 시 아군 위치는 참고 사항입니다.',
  '헬다이버는 죽지 않습니다. 교체됩니다.',
  '헬팟은 정확합니다. 그 자리의 아군이 부정확했습니다.',
  '슈퍼어스는 당신의 장비 선택을 존중합니다. 결과는 아닙니다.',
  '자유를 나눠 드립니다. 한 발씩.',
  '훈련은 20분이었습니다. 충분했습니다.',
  '오늘의 로드아웃이 내일의 전설. 내일까지 살아 있다면.',
  '채권을 구매하십시오. 민주주의에는 예산이 필요합니다.',
  '스트라타젬 오입력은 개인 책임. 결과는 팀 책임.',
  '장비 점검을 마친 당신, 이미 상위 12%입니다.',
]
export const SLOGAN_EXEMPLARY = '모범 헬다이버 발견. 진리부가 주목합니다.'

export const copy = {
  broadcast: '진리부 방송',
  permitTitle: '수호부 출격 허가서',
  permitUnsaved: '미저장',
  stampHold: '승인 보류',
  stampTreason: '반역 적발',
  stampApproved: '진리부 승인',
  stampApprovedShort: '승인',
  stampTreasonShort: '반역',
  stampHoldShort: '보류',
  violations: '위반 사항',
  save: '저장',
  duplicate: '복제',
  image: '이미지',
  briefing: '브리핑',
  reset: '초기화',
  delete: '삭제',
  settings: '설정',
  credits: '크레딧',
  savedLoadouts: '저장된 로드아웃',
  newLoadout: '신규 배정',
  defaultLoadoutName: '기본',
  untitledLoadout: '이름 없는 로드아웃',
  loadoutName: '로드아웃 이름',
  close: '닫기',
  defaultLocked: '기본 로드아웃은 수호부 지급 구성이라 수정 · 말소할 수 없습니다. 바꾸려면 복제하십시오.',
  permitLocked: '수호부 지급 · 고정',
  lockedCell: '고정',
  emptyList: '복무 기록 없음. 민주주의는 미리 준비한 자의 것입니다.',
  dragHint: '끌어서 정렬',
  fold: '목록 접기',
  unfold: '목록 펼치기',
  menu: '메뉴',
  menuDelete: '삭제',
  stratagems: '스트라타젬',
  gear: '개인 장비',
  poolSize: '후보 수',
  pickOf: (n: number) => `${n}택1`,
  emptyCell: '선택',
  race: '종족',
  faction: '팩션',
  all: '전체',
  loading: '슈퍼어스 방송 수신 중',
  loadError: '데이터 수신 실패',
  retry: '재시도',
  deletedItem: '삭제된 아이템',
  undo: '되돌리기',
  noticeTitle: '수호부 통지',
  noticeSaved: '로드아웃이 기록 보관소에 저장됐습니다.',
  noticeCreated: '새 허가서가 발급됐습니다.',
  noticeDuplicated: '복제본이 발급됐습니다.',
  noticeDeleted: '기록이 말소됐습니다.',
  noticeRestored: '기록이 복원됐습니다.',
  noticeImageSaved: '허가서 사본을 출력했습니다.',
  noticeImageFailed: '허가서 사본을 출력하지 못했습니다. 다시 시도하십시오.',
  noticeImported: (n: number) => `${n}건을 가져왔습니다.`,
  noticeFontFallback: '서체를 내려받지 못해 시스템 서체로 출력했습니다.',
  reeducationTitle: '재교육 동의서',
  reeducationBody: (what: string) => `${what} 이 조치는 되돌릴 수 없습니다. 진리부는 당신의 협조에 감사합니다.`,
  reeducationReset: '이 허가서의 배정 내역을 전부 지웁니다.',
  reeducationReplace: '기존 기록 전체를 가져온 파일로 교체합니다. 직전 상태는 백업으로 남습니다.',
  agree: '동의합니다',
  dirtyTitle: '저장하지 않은 변경',
  dirtyBody: '작성 중인 허가서를 저장하지 않았습니다. 버리고 계속할까요?',
  discardAndContinue: '버리고 계속',
  keepEditing: '계속 작성',
  importMerge: '병합',
  importReplace: '교체',
  importSettingsToo: '설정도 가져오기',
  importInvalid: '이 파일은 로드아웃 빌더 형식이 아닙니다.',
  exportJson: 'JSON 내보내기',
  importJson: 'JSON 가져오기',
  restoreBackup: '마지막 백업 복원',
  noBackup: '보관된 백업이 없습니다.',
  settingsEagle: '이글 경고 기준',
  settingsEagleN: (n: number) => `${n}개 이상`,
  settingsData: '데이터',
  settingsBackpack: '배낭 · 지원무기 중복 경고',
  settingsDisposable: '일회용 지원무기 제외',
  settingsName: '이름 표기',
  settingsTheme: '테마',
  settingsWarbonds: '보유 채권',
  settingsSuperstore: '슈퍼 스토어 포함',
  warbondsAll: '전부 보유',
  warbondsReset: '초기화',
  warbondsResetHint: '기본 채권(헬다이버 출동!)만 보유 상태로 되돌립니다.',
  themeConsole: '줄무늬 콘솔',
  themeTeletype: '텔레타이프',
  nameKo: '한글',
  nameBoth: '한 + 영',
  nameEn: '영문',
  /** 위반 목록: 등급 · 제목 · 슬롯 · 판정 태그. 줄글 대신 표처럼 읽히게 짧게. */
  levelHard: '위반',
  levelSoft: '주의',
  levelInfo: '안내',
  warnTitle: {
    backpack: '배낭 중복',
    support_weapon: '지원무기 중복',
    eagle: (n: number) => `이글 ${n}`,
    eagleSoft: (n: number) => `이글 최대 ${n}`,
    empty: (n: number) => `미배정 ${n}`,
  },
  warnVerdict: {
    backpackHard: '반역 혐의',
    backpackSoft: '조합 주의',
    supportHard: '어깨끈 부족',
    supportSoft: '조합 주의',
    eagleHard: '조종사 과로',
    eagleSoft: '조합 주의',
    empty: '승인 보류',
  },
  slotLabel: '슬롯',
  okAll: '위반 없음',
  okVerdict: '출격 적합',
  searchPlaceholder: '이름으로 검색',
  pickerStrat: (n: number) => `스트라타젬 ${n}`,
  pickerStratTitle: '스트라타젬 선택',
  pickerGearTitle: '개인 장비 선택',
  pickerCurrent: '현재',
  pickerReplace: '교체',
  slotN: (n: number) => `슬롯 ${n}`,
  clear: '해제',
  pickerUnowned: '미보유',
  pickerStoreOff: '스토어 제외',
  pickerNone: '조건에 맞는 항목이 없습니다.',
  wikiOpen: 'wiki에서 보기',
  wikiOpenHint: 'wiki에서 보기: 우클릭 또는 길게 누르기',
  warbondPage: (n: number) => `${n}페이지`,
  broadcastChannel: '// 채널 07',
  crashTitle: '수호부 단말 오류',
  crashBody: '화면을 그리지 못했습니다. 저장된 기록은 이 브라우저에 그대로 남아 있습니다. 편집 중인 허가서를 버리면 대부분 다시 열립니다.',
  crashDiscard: '편집 중인 허가서 버리고 다시 열기',
  crashBackup: '저장 기록 내려받기',
  creditsTitle: '공로 인정서',
  creditsSub: '관리 민주주의를 위한 자발적 노동에 관하여',
  creditsMakerLabel: '제작 · 운용',
  creditsMaker: 'rogue992',
  creditsMakerNote: '슈퍼어스 시민. 출격 전 장비 점검을 게임 밖으로 끌어냈다. 진리부는 이 행위를 애국으로 분류했다.',
  creditsSectionSources: '전공 기록 (출처)',
  creditsSectionLegal: '진리부 고지',
  creditsWiki: '아이템 데이터 · 무기 · 방어구 렌더',
  creditsWikiNote: (version: string, fetched: string) => `데이터 기준 패치 ${version}, 수집 ${fetched}. 텍스트 CC BY-NC-SA 4.0.`,
  creditsNvig: '스트라타젬 아이콘',
  creditsNvigNote: '전 헬다이버가 알아보는 그 아이콘. 정직하게 SVG로.',
  creditsSes: '한글 명칭 초기 데이터 · 배치 참고',
  creditsSesName: 'SES 자기 결정의 전달자',
  creditsSesNote: '기본 로드아웃도 이 함선의 것을 그대로 지급받았다.',
  creditsLegal1: 'HELLDIVERS 2 © Arrowhead Game Studios AB. 이 도구는 비상업 개인 프로젝트이며 Arrowhead · Sony와 무관합니다.',
  creditsLegal2: '이 도구의 코드는 MIT. 데이터와 이미지는 각 출처의 조건을 따릅니다.',
  creditsStamp: '진리부 검열 통과',
  creditsClose: '경례 후 닫기',
} as const
